
document.write('<scri'+'pt src="/toaster/utils.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/local_storage.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/use_case.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/gui.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/glue.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/models.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/fake_server_side.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/playlist_gui.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/blog_gui.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/podcasts_gui.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/blog_usecase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/podcasts_usecase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/playlist_usecase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/toaster/app.js"></scr'+'ipt>')